DronePermitSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Main.urls')),
    path('auth/',include('Authentication.urls')),
    path('pay/',include('Payment.urls')),
]

Main/urls.py
from django.urls import path,include
from . import views
from .views import *

app_name = 'Main'

urlpatterns = [
    path('',views.home_page, name="home"),
    path('dronepermit',views.dronepermit.as_view(), name="dronepermit"),
    # path('dronepermit',views.drone_permit, name="dronepermit"),
    # path('userprofile/',views.userprofile, name="userprofile"),
    path('userprofile/<int:owner_id>',userprofile, name="userprofile"),
    path('permits/', permits, name='permits'),
    path('update_status/', views.update_status, name='update_status'),
    # path('signin/', views.signin, name='signin'),
    # path('signup', views.signup, name='signup'),
]

Payment/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('payment/', payment, name='payment'),
    #path('signup/', signup, name='signup'),
]

Main/models.py
from django.db import models
#from Authentication.models import User

class Owner(models.Model):
    #oid = models.ForeignKey(User, on_delete= models.CASCADE, default='user',primary_key=True)
    fname = models.CharField(max_length=30,verbose_name="First Name")
    lname = models.CharField(max_length=30,verbose_name="Last Name")
    email = models.EmailField(max_length=254,unique=True,verbose_name="Email")
    tele_no = models.CharField(max_length=10, unique=True,verbose_name="Phone No.")
    pilot_fname = models.CharField(max_length=30,verbose_name="Pilot First Name")
    pilot_lname = models.CharField(max_length=30,verbose_name="Pilot Last Name")
    pilot_email = models.EmailField(max_length=254,verbose_name="Pilot Email")
    pilot_tele_no = models.CharField(max_length=10,verbose_name="Pilot Phone No.")

    def __str__(self):
        return str(self.fname) + ' ' + str(self.lname) 

class Drone(models.Model):
    CATEGORIES = [
        ("A","A"),("B","B"),("C","C"),("D","D"),
    ]

    TYPES = [
        ('1',"Multi-Rotor"),('2',"Fixed-Wing"),('3',"Single-Rotor"),('4',"Fixed-Wing Hybrid VTOL"),
    ]
    owners = models.ForeignKey(Owner, on_delete=models.CASCADE, related_name='drones', db_column='owners_id', null=True)
    modelno = models.CharField(max_length=30, null=False, blank=False,verbose_name="Model No.")
    category = models.CharField(max_length=1,choices=CATEGORIES,verbose_name="Category")
    types = models.CharField(max_length=10,choices=TYPES,verbose_name="Type")
    weight = models.DecimalField(max_digits=4, decimal_places=2,verbose_name="Weight")
    max_takeoff = models.CharField(max_length=30, null = False , blank = False,verbose_name="Maximum TakeOff")
    manufacturer = models.CharField(max_length=100, verbose_name="Manufacturer Name")
    reg_id = models.CharField(max_length=10, unique=True, null = True, blank = False, verbose_name="Drone Registration No.")

    def __str__ (self):
        return self.modelno
    
class Area(models.Model):
    DISTRICTS = [
        ('Achham', 'Achham'), ('Arghakhanchi', 'Arghakhanchi'), ('Baglung', 'Baglung'), ('Baitadi', 'Baitadi'), ('Bajhang', 'Bajhang'),
        ('Bajura', 'Bajura'), ('Banke', 'Banke'), ('Bara', 'Bara'), ('Bardiya', 'Bardiya'), ('Bhaktapur', 'Bhaktapur'),
        ('Bhojpur', 'Bhojpur'), ('Chitwan', 'Chitwan'), ('Dadeldhura', 'Dadeldhura'), ('Dailekh', 'Dailekh'), ('Dang', 'Dang'),
        ('Darchula', 'Darchula'), ('Dhading', 'Dhading'), ('Dhankuta', 'Dhankuta'), ('Dhanusa', 'Dhanusa'), ('Dolakha', 'Dolakha'),
        ('Dolpa', 'Dolpa'), ('Doti', 'Doti'), ('Eastern Rukum', 'Eastern Rukum'), ('Gorkha', 'Gorkha'), ('Gulmi', 'Gulmi'),
        ('Humla', 'Humla'), ('Ilam', 'Ilam'), ('Jajarkot', 'Jajarkot'), ('Jhapa', 'Jhapa'), ('Jumla', 'Jumla'),
        ('Kailali', 'Kailali'), ('Kalikot', 'Kalikot'), ('Kanchanpur', 'Kanchanpur'), ('Kapilvastu', 'Kapilvastu'), ('Kaski', 'Kaski'),
        ('Kathmandu', 'Kathmandu'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Khotang', 'Khotang'), ('Lalitpur', 'Lalitpur'), ('Lamjung', 'Lamjung'),
        ('Mahottari', 'Mahottari'), ('Makwanpur', 'Makwanpur'), ('Manang', 'Manang'), ('Morang', 'Morang'), ('Mugu', 'Mugu'),
        ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Nawalpur', 'Nawalpur'), ('Nuwakot', 'Nuwakot'), ('Okhaldhunga', 'Okhaldhunga'),
        ('Palpa', 'Palpa'), ('Panchthar', 'Panchthar'), ('Parbat', 'Parbat'), ('Parsa', 'Parsa'), ('Pyuthan', 'Pyuthan'),
        ('Ramechhap', 'Ramechhap'), ('Rasuwa', 'Rasuwa'), ('Rautahat', 'Rautahat'), ('Rolpa', 'Rolpa'), ('Rukum West', 'Rukum West'),
        ('Rupandehi', 'Rupandehi'), ('Salyan', 'Salyan'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Saptari', 'Saptari'), ('Sarlahi', 'Sarlahi'),
        ('Sindhuli', 'Sindhuli'), ('Sindhupalchok', 'Sindhupalchok'), ('Siraha', 'Siraha'), ('Solukhumbu', 'Solukhumbu'), ('Sunsari', 'Sunsari'),
        ('Surkhet', 'Surkhet'), ('Syangja', 'Syangja'), ('Tanahun', 'Tanahun'), ('Taplejung', 'Taplejung'), ('Terhathum', 'Terhathum'),
        ('Udayapur', 'Udayapur'), ('Western Rukum', 'Western Rukum')
    ]

    district = models.CharField(max_length = 255, choices = DISTRICTS,verbose_name="District")
    municipality = models.CharField(max_length=255,verbose_name="Municipality")
    wardno = models.PositiveIntegerField(null=True,verbose_name="Ward No.")
    areainsqm = models.CharField(max_length=10, null=False, blank=False, verbose_name="Area in Square Meter")

    def __str__(self):
        return self.municipality
    
class DronePermit(models.Model):
    STATUS = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]

    owner = models.ForeignKey(Owner, on_delete=models.SET_NULL, null=True, related_name= "drone_permits")
    drone = models.ForeignKey(Drone,on_delete=models.SET_NULL,null=True, related_name="owner")
    area = models.ForeignKey(Area,on_delete=models.SET_NULL,null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    purpose = models.CharField(max_length=255,verbose_name="Purpose of Flight")
    status = models.CharField(max_length=10, choices = STATUS, default='pending')

    def __str__(self):
        return str(self.owner) + '--'+ str(self.drone)

Payment/models.py
from django.db import models

# Create your models here.

Payment/views.py
from django.shortcuts import render

# Create your views here.
def payment(request):
    return render(request, 'payment.html')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drone Permit</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body >
    <header>
        <div class="nav">
            <div>
                <img src="{% static 'images/caanlogo.png' %}" height="100px" width="200px" alt="caan logo">
            </div>
        </div>

        <nav>

          <div class="menu">
            <ul>
              <li><a href="{% url 'Main:home' %}">Home</a></li>
              {% if request.user.is_user %}
              <li><a href="{% url 'Main:dronepermit' %}">Permit</a></li>
              {% endif %}
              <li><a href="{% url 'payment' %}">Donate</a></li>
              <ul>
              </div>
              <div class="log">
                <ul>
                  {% if user.is_authenticated %}
                  <li><a href="{% url 'logout' %}">Logout</a></li>
                      {% if request.user.is_user %}
                      <li><a href="#">Profile</a></li>  
                      {% endif %} 
                  {% else %}
                  <li><a href="{% url 'signin' %}">Login</a></li>
                  <li><a href="{% url 'signup' %}">Signup</a></li>
                  {% endif %}
                </ul>
              </div>
            </nav>
    </header>
    
    <!-- <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'Main:home' %}">
            <img src="{% static 'images/caanlogo.png' %}" alt="logo" id="logo">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Main:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Main:dronepermit' %}">Register</a>
              </li>
            </ul>
          </div>
        </div>
    </nav> -->

    {% block content %}

    {% endblock content %}
    
    <!-- <footer class="row">
        <div class="col-md-4">
          <p class="text-light">All Right Reserved &copy; Drone Services .</p>
        </div>

        <div class="col-md-4">
          <h3 class="text-light">Quick Links</h3>

          <ul style="list-style: none; padding-left: 0;">
            <li><a class="text-light" href="/about/content/About">About</a></li>
            <li><a class="text-light" href="/about/content/Policies">Policies</a></li>
            <li><a class="text-light" href="/about/content/Contacts">Contacts</a></li>
          </ul>
        </div>

        <div class="col-md-4">
          <h4 class="text-light">Subscribe Us:</h4>
          <form action="">
            <input type="email" class="form" name="email" 
              placeholder="Your Email">
            <input type="submit" class="btn btn-info" value="Subscribe">
          </form>
        </div>
      </footer> -->
      <footer>
        <p>&copy; 2023 Drone Services. All rights reserved.</p>
      </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

    <script src="/static/js/index.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section id="home">
  <div class="hero">
    <h1>Drone Services</h1>
    
    <p>At our website, we offer a comprehensive and hassle-free service for granting drone permits. Our goal is to make the process of obtaining a drone permit as smooth and efficient as possible. We understand the importance of operating drones legally and safely, and that's why we provide a streamlined permit application process. Our team of experts ensures that your application is carefully reviewed, and we strive to deliver permits promptly, allowing you to start your drone operations without unnecessary delays. We pride ourselves on our affordable fee structure, making it accessible for drone enthusiasts and professionals alike. Our dedicated customer service team is always ready to assist you, addressing any queries or concerns you may have throughout the permit application process. We utilize the latest technology to ensure accuracy and up-to-date compliance with regulations. With our fast response times, you can expect efficient communication and timely updates on your permit status. Trust us to provide a reliable and efficient service for all your drone permit needs.</></p>
  </div>
  <div class="image">
  <img src="{% static 'images/drone.png' %}" width="500px" height="400px" alt="drone">
    
  </div>
</section>
{% endblock content %}

templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block title %} payment {% endblock title %}

{% block content %}

<style>
    .center {
  margin: auto;
  width: 50%;
  border: 3px solid green;
  padding: 10px;
}
</style>
<h1> This donation is for the Site</h1>
<marquee scrollamount="20">Please help us to keep the system running with your little help!!</marquee>
    <!-- <div class="paypal-button-container">
        <button value="donate">donate</button>
    </div> -->
    
        <div id="paypal-button-container" class="center">
            <p>Payment conformation for $5 donation:</p>
        </div>
<script src="https://www.paypal.com/sdk/js?client-id=AVeT07nK_pAYI3X3QOE5JjH8O-nvOvs1AfeHHZlGs_t6tneZBKX9KJfyO3jzllxXHzv-y-RUxf1dnHYY&currency=USD"></script>

  <script>
    var total = '5'
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

          style:{
            color: 'blue',
            shape: 'pill',
            size: 'responsive',
            label: 'paypal',
          },
            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: 50
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    submitFormData()
                });
            }


        }).render('#paypal-button-container');
    </script>
{% endblock %}

templates/permits.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <link rel="stylesheet" href="{% static 'css/table.css' %}">

    <div class="container mt-5 px-2">
        
        <div class="table-responsive">
            <h2 style="text-align: center;"><strong>Drone Permits</strong></h2>
            {% if permit_list %}
                <table class="table table-responsive ">
                    
                    <thead>
                        <tr class="bg-light">
                            <th scope="col" width="15%">Permit ID</th>
                            <th scope="col" width="20%">Date Created</th>
                            <th scope="col" width="10%">Status</th> 
                            <th scope="col" width="20%">Owner Name</th>
                            <th scope="col" width="20%">Drone Details</th>
                            <th scope="col" width="80%">Drone Registration No</th>
                            <th scope="col" width="20%">Location</th>
                            <th scope="col" width="60%">Change Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for permit in permit_list %}
                        <tr>
                        <td>{{ permit.id }}</td>
                        <td>{{ permit.date_created }}</td>
                        <td><i class="fa fa-check-circle-o green"></i><span class="ms-1">{{ permit.status }}</span>
                        </td>
                        
                        <td><img src="https://i.imgur.com/VKOeFyS.png" width="25"> {{ permit.owner.fname }} {{ permit.owner.lname }}</td>
                        <td>{{ permit.drone.modelno }}, {{ permit.drone.manufacturer }}</td>
                        <td>{{ permit.drone.reg_id }}</td>
                        <td>{{ permit.area.municipality }}-{{ permit.area.wardno }}, {{ permit.area.district }}</td>
                        <td>
                            <form method="POST" action="{% url 'Main:update_status' %}">
                                {% csrf_token %}
                                <input type="hidden" name="permit_id" value="{{ permit.id }}">
                                <select name="status" id="status">
                                    <option value="pending">Pending</option>
                                    <option value="approved">Approved</option>
                                    <option value="rejected">Rejected</option>
                                </select>
                                <input type="submit" value="Update">
                            </form>
                        </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No permits found.</p>
            {% endif %}
    
        </div>
        
    </div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h2 style="text-align: center;">Welcome, {{ owner.fname }} {{ owner.lname }}</h2>

    <div class="container mt-5 px-2">
        <div class="table-responsive">
            {% if owner.drones.all %}
            <table class="table table-responsive">
                <h3 style="text-align: center;">Drone Details</h3>
                {% for drone in owner.drones.all %}
               <thead>
                    <tr class="bg-body-tertiary">
                        <th>Model No</th>
                        <th>Category</th>
                        <th>Type</th>
                        <th>Weight</th>
                        <th>Maximum Takeoff</th>
                        <th>Drone Registration No</th>
                        <th>Manufacturer</th>
                    </tr>
               </thead> 
               <tbody>
                <tr>
                    <td>{{ drone.modelno }}</td>
                    <td>{{ drone.get_category_display }}</td>
                    <td>{{ drone.get_types_display }}</td>
                    <td>{{ drone.weight }}</td>
                    <td>{{ drone.max_takeoff }}</td>
                    <td>{{ drone.reg_id }}</td>
                    <td>{{ drone.manufacturer }}</td>
                </tr>
               </tbody>
               {% endfor %}
            </table>
            {% else %}
            <p>No drones found.</p>
            {% endif %}
        </div>
    </div>

    <div class="container mt-5 px-2">
        <div class="table-responsive">
            {% if owner.drone_permits.all %}
            <table class="table table-responsive">
                <h3 style="text-align: center;">Permit Detail</h3>
                {% for permit in owner.drone_permits.all %}
                <thead>
                    <tr class="bg-light">
                        <th>Location</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ permit.area.municipality }}-{{ permit.area.wardno }}, {{ permit.area.district }}</td>
                        <td>{{ permit.status }}</td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
            {% else %}
                <p>No permits found.</p>
                <a href="{% url 'Main:dronepermit' %}">Apply for a Permit</a>
            {% endif %}
        </div>
    </div>
    
{% endblock %}

templates/registrationform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div>
    <h1>Permit Application Form</h1>

    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label><h3>Drone Owner Details</h3></label>
    {{forms.owner_form.as_p}}
    <label><h3>Drone Details</h3></label>
    {{forms.drone_form.as_p}}
    <label><h3>Area Details</h3></label>
    {{forms.area_form.as_p}}

    {{forms.dronepermit_form.as_p}}
      <!-- <h3>Drone Owner's details</h3>
      <label for="firstName">First Name:</label>
      <input type="text" id="firstName" name="firstName" required />

      <label for="lastName">Last Name:</label>
      <input type="text" id="lastName" name="lastName" required />

      <label for="email">Email:</label>
      <input type="email" id="email" name="email" required />

      <label for="phone">Phone Number:</label>
      <input type="tel" id="phone" name="phone" required />

      <h3>Drone pilot's details</h3>
      <label for="pfirstName">First Name:</label>
      <input type="text" id="pfirstName" name="pfirstName" required />

      <label for="plastName">Last Name:</label>
      <input type="text" id="plastName" name="plastName" required />

      <label for="pemail">Email:</label>
      <input type="email" id="pemail" name="pemail" required />

      <label for="pphone">Phone Number:</label>
      <input type="tel" id="pphone" name="pphone" required />

      <h3>Drone Details</h3>
      <label for="modelNo">Model no.</label>
      <input type="text" id="modelNo" name="modelNo" required />

      <label for="category">Category</label>
      <select name="category" id="category" required>
        <option value="A">A</option>
        <option value="B">B</option>
        <option value="C">C</option>
        <option value="D">D</option>
      </select>

      <label for="maximumTakeoff">Maximum Takeoff in meter</label>
      <input type="text" id="maximumTakeoff" name="maximumTakeoff" required />

      <label for="typeofAircraft">Type of Aircraft</label>
      <select name="typeofAircraft" id="typeofAircraft" required>
        <option value="Multi-Rotor">Multi-Rotor</option>
        <option value="Fixed-Wing">Fixed-Wing</option>
        <option value="Single-Rotor">Single-Rotor</option>
        <option value="Fixed-Wing Hybrid VTOL">Fixed-Wing Hybrid VTOL</option>
      </select>

      
      <label for="weight">Weight</label>
      <input type="number" id="weight" name="weight" required />

      <label for="manufacturer">Manufacturer</label>
      <input type="text" id="manufacturer" name="manufacturer" required />


      <h3>Area to use</h3>
      <label for="district">District</label>
      <select id="districtSelect" name="district">
        
      </select>

      <label for="muni">Municipality</label>
      <input type="text" id="muni" name="muni" required />
      
      <label for="wardNo">Ward No.</label>
      <input type="number" id="wardNo" name="wardNo" required />

      <label for="area">Area in square meter</label>
      <input type="text" id="area" name="area" required />

      <label for="pur">Purpose</label>
      <input type="text" id="pur" name="pur" required /> -->

      <input type="submit" value="Submit">
    </form>
  </div>

    <script>
      var districts = [
        "Achham", "Arghakhanchi", "Baglung", "Baitadi", "Bajhang", "Bajura", "Banke", "Bara", "Bardiya", "Bhaktapur", "Bhojpur", "Chitwan", "Dadeldhura", "Dailekh", "Dang", "Darchula", "Dhading", "Dhankuta", "Dhanusa", "Dholkha", "Dolpa", "Doti", "Eastern Rukum", "Gorkha", "Gulmi", "Humla", "Ilam", "Jajarkot", "Jhapa", "Jumla", "Kailali", "Kalikot", "Kanchanpur", "Kapilvastu", "Kaski", "Kathmandu", "Kavrepalanchok", "Khotang", "Lalitpur", "Lamjung", "Mahottari", "Makwanpur", "Manang", "Morang", "Mugu", "Mustang", "Myagdi", "Nawalpur", "Nuwakot", "Okhaldhunga", "Palpa", "Panchthar", "Parbat", "Parsa", "Pyuthan", "Ramechhap", "Rasuwa", "Rautahat", "Rolpa", "Rukum", "Rupandehi", "Salyan", "Sankhuwasabha", "Saptari", "Sarlahi", "Sindhuli", "Sindhupalchok", "Siraha", "Solukhumbu", "Sunsari", "Surkhet", "Syangja", "Tanahu", "Taplejung", "Terhathum", "Udayapur", "Western Rukum"
      ];
    
      // Get the select element
      var selectElement = document.getElementById("districtSelect");
    
      // Populate the select element with options
      for (var i = 0; i < districts.length; i++) {
        var option = document.createElement("option");
        option.text = districts[i];
        option.value = districts[i];
        selectElement.add(option);
      }
    </script>
    
{% endblock content %}

templates/signin.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Signin {% endblock title %}

{% block content %}

  <style>
body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
}

h1 {
  text-align: center;
  margin-top: 20px;
}

.buttons-container {
  display: flex;
  justify-content: center;
  margin-top: 20px;
}

button {
  margin: 0 10px;
  padding: 10px 20px;
  font-size: 16px;
  background-color: #333;
  color: #fff;
  border: none;
  cursor: pointer;
}

form {
  max-width: 300px;
  margin: 0 auto;
}

label {
  display: block;
  margin-bottom: 5px;
}

input[type="text"],
input[type="password"] {
  width: 100%;
  padding: 10px;
  margin-bottom: 10px;
}

button[type="submit"] {
  background-color: #333;
  color: #fff;
  border: none;
  padding: 10px;
  cursor: pointer;
}

  </style>
</head>
<body>
  <h1>Login</h1>

  <span class="mb-0 text-muted">
    {% if msg %}
        {{ msg | safe }}
    {% else %}
        Login page
    {% endif %}
  </span>

  <form action="" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <!-- <input type="text" id="username" name="username" required> -->
    {{ form.username }}


    <label for="password">Password:</label>
    <!-- <input type="password" id="password" name="password" required> -->
    {{ form.password }}

    <br> 
    <button type="submit">Login</button><br><br>
    <a href="{% url 'signup' %}">Don't have an account?</a><br>
    <a href="/admin">Admin Login</a>
  </form>

  {% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Signup {% endblock title %}

{% block content %}
  <style>
    body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
}

h1 {
  text-align: center;
  margin-top: 20px;
}

form {
  max-width: 300px;
  margin: 0 auto;
}

label {
  display: block;
  margin-bottom: 5px;
}

input[type="text"],
input[type="email"],
input[type="tel"],
input[type="password"] {
  width: 100%;
  padding: 10px;
  margin-bottom: 10px;
}

button[type="submit"] {
  background-color: #333;
  color: #fff;
  border: none;
  padding: 10px;
  cursor: pointer;
}

.error-message {
  color: red;
  margin-top: 5px;
}

  </style>


<body>
<!-- {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}  -->

  <h1>Create Account:</h1>

  <span class="mb-0 text-muted">
    {% if msg %}
        {{ msg | safe }}
    {% else %}
        Login page
    {% endif %}
  </span>

  <form action="" method="POST">
    {% csrf_token %}
    <!-- <label for="firstName">First Name:</label>
    <input type="text" id="firstName" name="firstName" required>

    <label for="lastName">Last Name:</label>
    <input type="text" id="lastName" name="lastName" required>

     -->

    <label for="username">Username:</label>
    <!-- <input type="text" id="username" name="username" required> -->
    {{ form.username }}

    <label for="email">Email:</label>
    <!-- <input type="email" id="email" name="email" required> -->
    {{ form.email}}

    <label for="password">Password:</label>
    <!-- <input type="password" id="password" name="password" required> -->
    {{ form.password1 }}

    <label for="confirmPassword">Confirm Password:</label>
    <!-- <input type="password" id="confirmPassword" name="confirmPassword" required> -->
    {{ form.password2 }}

    <p>Please select your account type:</p>

    <!-- <input type="radio" id="user" name="user" value="user">User<br>
    <input type="radio" id="officer" name="user" value="officer">Officer<br> -->
    <div class="d-flex mb-5 align-items-center">
      <label class="control control--checkbox mb-0"><span class="caption">Admin</span>
          {{ form.is_admin }}
        <!-- <div class="control__indicator"></div> -->
      </label>
    <br>
      <label class="control control--checkbox mb-0"><span class="caption">User</span>
          {{ form.is_user }}
        <!-- <div class="control__indicator"></div> -->
      </label>
      <br>
      <label class="control control--checkbox mb-0"><span class="caption">Officer</span>
          {{ form.is_officer }}
        <!-- <div class="control__indicator"></div> -->
      </label>
    </div>
      <span class="text-error">{{ form.errors }}</span>
    
    <br>
    <button type="submit">Create</button><br><br>
    <a href="{% url 'signin' %}">Already have an account?</a>
  </form><br><br>
 
</body>
{% endblock content %}